export const allColumns = {
    index: "N°",
    matricule: "N° MAT",
    name: "NOM ET PRENOMS",
    poste: "POSTE / FONCTION",
    department: "SERVICE",
    sexe: "SEXE",
    situationMatrimoniale: "SITUATION MATRIMONIALE",
    enfants: "ENFANTS",
    Date_Naissance: "DATE NAISSANCE",
    Lieu_Naissance: "LIEU NAISSANCE",
    email: "CONTACT",
    status: "STATUT",
    CNPS: "CNPS",
    dateEmbauche: "PRISE DE SERVICE",
    Date_Depart: "DATE DÉPART",
    age: "ÂGE",
    profile: "PROFIL",
    Region: "RÉGION",
    Departement: "DÉPARTEMENT",
    subPrefecture: "SOUS-PRÉFECTURE",
    Village: "VILLAGE / LOCALITÉ",
} as const;

export const chiefColumns = {
    index: "N°",
    matricule: "N° MAT",
    name: "NOM ET PRENOMS",
    sexe: "SEXE",
    situationMatrimoniale: "SITUATION MATRIMONIALE",
    enfants: "ENFANTS",
    poste: "TITRE / FONCTION",
    statutChef: "STATUT DE CHEF",
    profile: "PROFIL",
    contact: "CONTACT",
    status: "STATUT",
    Region: "RÉGION",
    Departement: "DÉPARTEMENT",
    subPrefecture: "SOUS-PRÉFECTURE",
    Village: "VILLAGE / LOCALITÉ",
    Num_Decision: "RÉFÉRENCE",
    photoUrl: "PHOTO",
} as const;

export type ColumnKeys = keyof typeof allColumns | keyof typeof chiefColumns;
