export const IVORIAN_REGIONS = [
    "Abidjan",
    "Agnéby-Tiassa",
    "Bafing",
    "Bagoué",
    "Bélier",
    "Béré",
    "Bounkani",
    "Cavally",
    "Folon",
    "Gbêkê",
    "Gbôklé",
    "Gôh",
    "Gontougo",
    "Grands-Ponts",
    "Guémon",
    "Hambol",
    "Haut-Sassandra",
    "Iffou",
    "Indénié-Djuablin",
    "Kabadougou",
    "Lôh-Djiboua",
    "Marahoué",
    "Mé",
    "Moronou",
    "Nawa",
    "N’Zi",
    "Poro",
    "San-Pédro",
    "Sud-Comoé",
    "Tchologo",
    "Tonkpi",
    "Worodougou",
    "Yamoussoukro"
] as const;

export type IvorianRegion = typeof IVORIAN_REGIONS[number];
