export const PRESS_CONFLICT_CATEGORIES = [
  "Conflit",
  "Fait signalé",
  "Alerte",
  "Tension communautaire",
  "Autre"
] as const;
export type PressConflictCategory = typeof PRESS_CONFLICT_CATEGORIES[number] | (string & {});

export const PRESS_CONFLICT_TYPES = [
  "Foncier",
  "Affrontement intercommunautaire",
  "Désignation des chefs",
  "Problème de justice",
  "Orpaillage",
  "Succession",
  "Politique",
  "Affaires civiles",
  "Autre"
] as const;
export type PressConflictType = typeof PRESS_CONFLICT_TYPES[number] | (string & {});

export const PRESS_CONFLICT_STATUSES = [
  "En cours",
  "À suivre",
  "Résolu",
  "Résolu (juridiquement)",
  "Résolu (médiation)",
  "Résolu (calme revenu)",
  "Résolu (localement) / En cours (national)",
  "En cours (sanctions présidentielles annoncées)",
  "En cours (appel)",
  "En cours (site recolonisé puis re-démantelé)",
  "En cours (procédure judiciaire ouverte)",
  "En cours (deux procédures parallèles)",
  "En cours (négociation engagée)",
  "En cours (recommandations attendues)",
  "Clos (drame)",
  "Clos (décès)",
  "Clos (rapport historique 2022)",
  "Clos (départ du témoin)",
  "Classé sans suite"
] as const;
export type PressConflictStatus = typeof PRESS_CONFLICT_STATUSES[number] | (string & {});

export interface PressConflict {
  id: string;
  orderNumber?: number; // N°
  trackingId?: string; // Ex: VEILLE-2026-001
  dateOfFacts: string; // Date des faits
  source: string; // Source / Journal
  region: string; // Région
  locality: string; // Localité
  department?: string; // Département
  subPrefecture?: string; // Sous-préfecture
  latitude?: number; // Latitude
  longitude?: number; // Longitude
  category: PressConflictCategory; // Catégorie
  conflictType: PressConflictType; // Type de conflit
  description: string; // Description des faits
  status: PressConflictStatus; // Statut du suivi
  observations?: string; // Observations
  attachmentUrl?: string; // Lien pièce jointe / scan
  createdAt?: string;
  updatedAt?: string;
}

export const INITIAL_PRESS_CONFLICTS: Omit<PressConflict, "id">[] = [
  {
    "orderNumber": 1,
    "trackingId": "VEILLE-2026-001",
    "dateOfFacts": "09/04/2026",
    "source": "L'Avenir n°1417",
    "region": "Région du Sud-Comoé",
    "locality": "Grand-Bassam",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Cas sensible : un souverain en exercice, débouté jusqu'au Conseil d'État, continuerait d'occuper des terres litigieuses au nom de l'étendue de son règne. L'inexécution des décisions de justice est ici le vrai problème elle expose l'institution traditionnelle au reproche de se placer au-dessus du droit, dans un dossier qui recoupe directement le thème « problème de justice ».",
    "status": "En cours",
    "observations": "Litige foncier opposant des propriétaires terriens \ndu village de Modeste"
  },
  {
    "orderNumber": 2,
    "trackingId": "VEILLE-2026-002",
    "dateOfFacts": "16/07/2026",
    "source": "Notre Voie n°7950",
    "region": "Région du Guémon",
    "locality": "Gblapleu / Guitrozon (Duékoué)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Différend sur les limites territoriales entre les deux villages. Les cultivateurs de Gblapleu dénoncent des agressions et la destruction/confiscation de leurs récoltes par des individus de Guitrozon qui revendiquent des droits coutumiers. Le chef de Gblapleu, Koué Antoine, alerte sur un climat d'insécurité permanent.",
    "status": "En cours",
    "observations": "Risque d'escalade sans médiation. Contexte national de sécurisation du foncier rural (AFOR, PRESFOR)."
  },
  {
    "orderNumber": 3,
    "trackingId": "VEILLE-2026-003",
    "dateOfFacts": "16/07/2026",
    "source": "Notre Voie n°7950",
    "region": "District Autonome d'Abidjan",
    "locality": "Éloka-To (Bingerville)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Ventes illicites de centaines de terrains du lotissement « Ato Lagoona » par Akosso Abé Jacob, ex porte-parole de la chefferie Dougbo, qui continuait de signer des attestations d'attribution alors que le pouvoir de sa génération avait pris fin en 2020. Écroué depuis le 27/05/2026 pour faux et usage de faux, plainte de la chefferie Tchagba. Préjudice estimé à plusieurs centaines de millions FCFA.",
    "status": "En cours",
    "observations": "Recoupe désignation des chefs (usurpation) et justice (détention, procédure pénale)."
  },
  {
    "orderNumber": 4,
    "trackingId": "VEILLE-2026-004",
    "dateOfFacts": "03-14/07/2026",
    "source": "Le Patriote n°7942 ; Le Nouveau Réveil n°7139 ; L'Inter n°8400",
    "region": "District Autonome d'Abidjan",
    "locality": "Bidjan-Té / Attecoubé Village",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Crise ouverte à la chefferie : destitution du chef Ahizi Eliam Djagoua Guy prononcée le 03/07/2026 par les contestataires (doyen Nanan Biégot Laurent, porte-parole Akébi Jean-Baptiste) pour gestion opaque des terres et baux signés (Frankgain, Addoha, Djé Loukou) sans validation de la notabilité. Le chef conteste la légitimité de la destitution (coutume Tchaman) et affirme qu'Akébi a été suspendu dès mars 2026 pour faux et usage de faux ; justice saisie des deux côtés.",
    "status": "En cours",
    "observations": "Versions frontalement opposées ; recoupe désignation des chefs et justice."
  },
  {
    "orderNumber": 5,
    "trackingId": "VEILLE-2026-005",
    "dateOfFacts": "07/07/2026 ; sanctions annoncées 06/08",
    "source": "Fraternité Matin n°18448 ; Le Jour Plus n°8428 (14/08)",
    "region": "District Autonome d'Abidjan",
    "locality": "M'Badon / Koumassi Campement",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "La chefferie de M'Badon revendique la propriété des terres du quartier Campement, acquises selon elle par les ancêtres au XIXe siècle. Des destructions d'habitations ont eu lieu (Procureur saisi) ; le 04/07, la notabilité a remis 4 tonnes de vivres aux déguerpis. Le 6 août 2026, le président Alassane Ouattara a annoncé, dans un message télévisé, des sanctions contre les auteurs de déguerpissements menés « en dehors du cadre légal » ; la chefferie de Koumassi campement (chef suprême Nanan Marcelin Koffi, chef traditionnel Nanan Affi Aka) a salué cette annonce dès le lendemain, y voyant un signal fort en faveur du respect des droits.",
    "status": "En cours (sanctions présidentielles annoncées)",
    "observations": "La chefferie attend sereinement les conclusions des enquêtes annoncées par la Présidence."
  },
  {
    "orderNumber": 5,
    "trackingId": "VEILLE-2026-005",
    "dateOfFacts": "07/07/2026",
    "source": "Fraternité Matin n°18448",
    "region": "District Autonome d'Abidjan",
    "locality": "M'Badon / Koumassi Campement",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "La chefferie de M'Badon revendique la propriété des terres du quartier Campement, acquises selon elle par les ancêtres au XIXe siècle. Des destructions d'habitations ont eu lieu (Procureur saisi) ; le 04/07, la notabilité a remis 4 tonnes de vivres aux déguerpis.",
    "status": "En cours",
    "observations": "La chefferie s'en remet aux magistrats sur les destructions."
  },
  {
    "orderNumber": 6,
    "trackingId": "VEILLE-2026-006",
    "dateOfFacts": "22/06/2026",
    "source": "Soir Info n°9482",
    "region": "District Autonome d'Abidjan",
    "locality": "Port-Bouët (Vridi 3, Vridi Canal, Cité Perdue, Toviato, Alaya)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Démolitions massives menées depuis le 03/06/2026 par le District autonome d'Abidjan ; les chefs de communautés (porte-parole Nanan Jean Martin Abolé N'Gbé) dénoncent des milliers de familles à la rue en saison des pluies, mairie écartée de la planification.",
    "status": "En cours",
    "observations": "Demandes : arrêt des démolitions sans relogement, plateforme de dialogue."
  },
  {
    "orderNumber": 8,
    "trackingId": "VEILLE-2026-008",
    "dateOfFacts": "12/05/2026",
    "source": "L'Inter n°8352",
    "region": "Région du Gôh",
    "locality": "Gagnoa / Gnagbodougnoa (30 villages)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Chefferies et populations de 30 villages exigent des comptes face à la société Lagune Exploration Afrique, dont le sous-traitant chinois IMR a démarré des forages sans concertation locale. Arrêt forcé des travaux depuis un mois ; mea culpa public du PDG Moumini Bictogo.",
    "status": "En cours",
    "observations": "Revendications : rencontres village par village, indemnisation, protection des sites sacrés."
  },
  {
    "orderNumber": 9,
    "trackingId": "VEILLE-2026-009",
    "dateOfFacts": "16/06/2026",
    "source": "L'Inter n°8379",
    "region": "À vérifier (région non précisée)",
    "locality": "Lopouafla",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Le chef du village You Bi Trazié et le géomètre Goulizan Bi Irié répondent aux accusations du colonel Jean-Claude Tibé (appropriation de terres, profanation de cimetière) dans le cadre d'un lotissement. Une décision de justice exécutoire reconnaît les droits de la famille Bonan sur les parcelles contestées.",
    "status": "En cours",
    "observations": "Versions contradictoires ; recoupe justice."
  },
  {
    "orderNumber": 10,
    "trackingId": "VEILLE-2026-010",
    "dateOfFacts": "23/06/2026 ; détails 26/08 et 02/09",
    "source": "Notre Voie n°7933 ; Le Francotireur n°138 (26/08), n°139 (02/09)",
    "region": "Région du Gbôklé",
    "locality": "Canton Kébé, 10 villages riverains du CNRA (Sassandra)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Depuis 2025, le CNRA fait état de différends fonciers avec plusieurs communautés riveraines de Sassandra, portant sur près de 280 hectares affectés en un an, répartis en quatre foyers : à Sassandra ville, décapage d'une jachère de 65 ha en avril 2025 sur instruction du maire selon le CNRA, aggravé en juillet 2026 par la destruction de 40 ha de cocoteraies (105 ha au total), le village de Niézeko y revendiquant des droits coutumiers ; à Bassa, un lotissement de 10 ha aurait débordé sur une parcelle voisine de 15 ha (65 ha de dégâts) ; à Lebleko, intervention d'un cadre se réclamant d'une autorisation préfectorale non produite (90 ha détruits malgré un ordre d'arrêt) ; à Vodiéko, destructions de palmeraies sur environ 75 ha, alors qu'une parcelle de 10 ha avait été cédée au village en 2024 pour sa relocalisation face à l'avancée de la mer. De nouveaux témoignages (02/09) précisent que la montée du niveau de la mer contraint plusieurs villages à se réinstaller en hauteur, nécessitant de nouvelles terres ; le CNRA verserait un soutien financier aux villages (700 000 FCFA récemment à Bassa) sans mécanisme clair de reddition de comptes. Une proposition de compromis émerge : une répartition 1/3-2/3, deux tiers des terres restitués aux communautés et un tiers conservé par le CNRA pour la recherche, sous procédure transparente.",
    "status": "En cours",
    "observations": "Dossier à quatre foyers de tension distincts ; une piste de compromis (1/3-2/3) commence à émerger. Recoupe orpaillage et désignation des chefs."
  },
  {
    "orderNumber": 10,
    "trackingId": "VEILLE-2026-010",
    "dateOfFacts": "23/06/2026",
    "source": "Notre Voie n°7933",
    "region": "Région du Gbôklé",
    "locality": "Canton Kébé, 10 villages riverains du CNRA (Sassandra)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Dix villages réclament le déclassement des terres occupées par le CNRA depuis 115 ans, qu'ils qualifient d'expropriation. Le CNRA maintient qu'elles relèvent du domaine public. Le chef de Kadrokpa 1 dénonce aussi l'orpaillage illégal sur le fleuve et les campements érigés en villages sans consultation des chefs coutumiers.",
    "status": "En cours",
    "observations": "Marches et interruptions d'activité du centre ; recoupe orpaillage et désignation des chefs."
  },
  {
    "orderNumber": 11,
    "trackingId": "VEILLE-2026-011",
    "dateOfFacts": "06/05/2026 (faits 2022)",
    "source": "Le Mandat n°4327",
    "region": "Région du Sud-Comoé",
    "locality": "Assomlan",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "En 2022, 3 hectares de mangrove rasés sur les terres coutumières d'Assomlan pour remblayage. Frayère principale détruite, revenus de pêche passés de 3-4M FCFA/an à moins de 400 000 FCFA. Le Conseil d'État a annulé le certificat foncier à l'origine du désastre.",
    "status": "Résolu (juridiquement)",
    "observations": "Dommage écologique irréversible malgré la victoire juridique."
  },
  {
    "orderNumber": 12,
    "trackingId": "VEILLE-2026-012",
    "dateOfFacts": "03/07/2026",
    "source": "Fraternité Matin n°18445",
    "region": "District Autonome d'Abidjan",
    "locality": "Elokato (Bingerville)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Un cratère d'érosion, provoqué selon la chefferie par le bitumage mal conçu du tronçon Bingerville-Elokato-Ebra (fin 2021), menace d'isoler ce village-presqu'île de 3 000 habitants. Cimetière à une dizaine de mètres du ravin ; école et dispensaire difficilement accessibles.",
    "status": "En cours",
    "observations": "Appel direct au Président de la République pour remblayage et caniveaux."
  },
  {
    "orderNumber": 13,
    "trackingId": "VEILLE-2026-013",
    "dateOfFacts": "10/07/2026",
    "source": "L'Inter n°8400",
    "region": "District Autonome d'Abidjan",
    "locality": "Elokaté",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Le patriarche Nanan Akomian Akandan (101 ans) relance un litige foncier avec la société Palmafrique sur plus de 1 260 hectares, mis à disposition de l'État dans les années 1960 avec rétrocession promise jamais honorée. Palmafrique conteste et qualifie l'affaire de « vieux dossier ».",
    "status": "En cours",
    "observations": "À vérifier : les faits sur l'accord verbal des années 1960 ne reposent que sur les déclarations du patriarche, non confirmés indépendamment."
  },
  {
    "orderNumber": 14,
    "trackingId": "VEILLE-2026-014",
    "dateOfFacts": "16/06/2026 (faits en cours)",
    "source": "Le Mandat n°4353",
    "region": "District Autonome d'Abidjan",
    "locality": "Anan (Bingerville)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Un ex-député de Touba, Dr Sako Mamadou, accusé d'avoir extorqué plus de 125 millions FCFA à la chefferie d'Anan en se faisant passer pour un émissaire du chef de l'État lors d'un conflit de succession coutumière, avec attestations de vente de terres antidatées. Un membre du comité foncier local est en détention depuis octobre 2025.",
    "status": "En cours",
    "observations": "Recoupe désignation des chefs et justice ; procédé reproduit dans d'autres villages Atchan."
  },
  {
    "orderNumber": 16,
    "trackingId": "VEILLE-2026-016",
    "dateOfFacts": "21-26/06/2026",
    "source": "Fraternité Matin n°18436, n°18439",
    "region": "Région de la Bagoué",
    "locality": "Kouto / Samorossoba",
    "category": "Conflit",
    "conflictType": "Affrontement intercommunautaire",
    "description": "Conflit foncier ancien (parcelle rizicole de 1 000 hectares sur les berges du fleuve Bagoué) ayant dégénéré le 21/06 en affrontements à la machette : une vingtaine de blessés. Calme revenu 5 jours après (patrouilles mixtes, sous-préfet sur le terrain), populations invitées à attendre la décision de justice.",
    "status": "En cours",
    "observations": "Des heurts similaires avaient eu lieu en 2025 ; conflit qui s'embrase à chaque campagne agricole."
  },
  {
    "orderNumber": 17,
    "trackingId": "VEILLE-2026-017",
    "dateOfFacts": "25/04/2026",
    "source": "L'Inter n°8341",
    "region": "Région de l'Iffou",
    "locality": "Kouassi-Diétèkro (près de Kongoti)",
    "category": "Conflit",
    "conflictType": "Affrontement intercommunautaire",
    "description": "Une bagarre entre orpailleurs clandestins a dégénéré en conflit opposant autochtones et allogènes. Plusieurs blessés dans les deux camps ; calme ramené par l'escadron mobile de la gendarmerie.",
    "status": "Résolu (calme revenu)",
    "observations": "Recoupe orpaillage ; la région connaît des tensions récurrentes liées à l'orpaillage clandestin et à la drogue."
  },
  {
    "orderNumber": 18,
    "trackingId": "VEILLE-2026-018",
    "dateOfFacts": "08/06/2026",
    "source": "Soir Info n°9479",
    "region": "District Autonome d'Abidjan",
    "locality": "Île Boulay 2 (Séguikro)",
    "category": "Conflit",
    "conflictType": "Affrontement intercommunautaire",
    "description": "Tensions entre habitants et communauté béninoise après l'agression à l'arme blanche du ressortissant béninois Lokossou Promice dans la nuit du 08/06. Démarche d'apaisement du CCBCI auprès du chef central Emmanuel Kouao Kouao, qui a posé une condition : laisser la justice faire son travail.",
    "status": "En cours",
    "observations": "Origine : différend familial ayant dégénéré ; dimension communautaire à nuancer."
  },
  {
    "orderNumber": 19,
    "trackingId": "VEILLE-2026-019",
    "dateOfFacts": "25/03/2026 (décision)",
    "source": "Le Mandat n°4316",
    "region": "District Autonome d'Abidjan",
    "locality": "Yopougon-Kouté",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Le Conseil d'État a annulé l'arrêté préfectoral nommant Apiti Apiti Clément chef du village, la procédure ayant violé les us et coutumes du peuple Atchan (surclassement sans consensus). Reprise du processus de désignation ; transition sous l'autorité du Nanan du village et du doyen de la génération Tchagba.",
    "status": "En cours",
    "observations": "Recoupe justice (décision du Conseil d'État en cours d'application)."
  },
  {
    "orderNumber": 20,
    "trackingId": "VEILLE-2026-020",
    "dateOfFacts": "07/06/2026",
    "source": "L'Inter n°8375",
    "region": "Région du Guémon",
    "locality": "Kiriao (commune de Facobly)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Vacance de la chefferie depuis deux ans (intérim Lucien Oulaï). Le 07/06/2026, les chefs de familles ont désigné le Pr Jean Pohé (ancien maire de Facobly, lignée de la chefferie). Rapport transmis à la Chambre régionale des rois et chefs du Guémon, verdict attendu.",
    "status": "À suivre",
    "observations": "Pas de conflit signalé à ce stade."
  },
  {
    "orderNumber": 21,
    "trackingId": "VEILLE-2026-021",
    "dateOfFacts": "03-06/06/2026",
    "source": "L'Inter n°8351 (08/06)",
    "region": "Région du Gbêké",
    "locality": "Diabo et Languibounou (département de Botro)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Des chefs de villages, tribus et cantons ont publiquement contesté la gestion de Nanan N'Goran Koffi 2, président de la Chambre régionale du Gbêké, lui reprochant des ingérences dans la désignation de certains chefs. Médiation traditionnelle engagée le 06/06 à Bouaké.",
    "status": "Résolu (médiation)",
    "observations": "Le ministre Jacques Assahoré Konan a condamné la sortie publique (vidéo virale)."
  },
  {
    "orderNumber": 22,
    "trackingId": "VEILLE-2026-022",
    "dateOfFacts": "22/06/2026",
    "source": "L'Inter n°8384",
    "region": "Région de la Nawa",
    "locality": "Buyo-ville",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Zagbaï Lognon Sébastien, désigné chef par consensus le 16/02/2026, a adressé un avertissement aux communautés qui envisageraient d'introniser leurs propres chefs sans son aval.",
    "status": "À suivre",
    "observations": "Signe d'un risque de chefferies parallèles."
  },
  {
    "orderNumber": 23,
    "trackingId": "VEILLE-2026-023",
    "dateOfFacts": "22/06/2026",
    "source": "Le Patriote n°7923",
    "region": "District Autonome d'Abidjan",
    "locality": "Yopougon (chefferie Wê)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Lors de l'inauguration du siège de la chefferie Wê, les chefs ont demandé une meilleure reconnaissance institutionnelle des chefferies communautaires et dénoncé l'existence de chefferies parallèles.",
    "status": "À suivre",
    "observations": ""
  },
  {
    "orderNumber": 24,
    "trackingId": "VEILLE-2026-024",
    "dateOfFacts": "03/07/2026",
    "source": "Le Patriote n°7942",
    "region": "Région du Bounkani",
    "locality": "Bouna et Doropo (chefferie Lobi)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Les chefs Lobi contestent le processus de désignation des représentants à la Chambre nationale, demandent la suspension des désignations pour Bouna et Doropo (motion au préfet, articles 12 et 21 de la loi n°2014-428). Dénoncent une marginalisation de la communauté Lobi.",
    "status": "En cours",
    "observations": "Avertissement sur le risque de fragilisation des équilibres sociaux dans cette région frontalière."
  },
  {
    "orderNumber": 25,
    "trackingId": "VEILLE-2026-025",
    "dateOfFacts": "25/04/2026 (faits)",
    "source": "Soir Info n°9440 (28/04)",
    "region": "District Autonome de Yamoussoukro",
    "locality": "N'Gokro (Yamoussoukro)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Succession bloquée après le décès du dernier chef. Ampoh N'Guessan Jean Pierre Omer plaide pour l'intronisation rapide du chef déjà désigné par les chefs de lignage (accord du chef de canton Akouè), au sein de la famille du patriarche Kouassi N'Goh.",
    "status": "En cours",
    "observations": "Distinct du N'Gokro d'Alépé (autre localité homonyme)."
  },
  {
    "orderNumber": 26,
    "trackingId": "VEILLE-2026-026",
    "dateOfFacts": "04/04/2026 (procédure lancée)",
    "source": "L'Intelligent n°5884 (06/05)",
    "region": "Région du Gbêké",
    "locality": "Akawa (canton N'dranouan, Bouaké)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Procédure de destitution engagée depuis le 04/04/2026 par la mutuelle de développement locale contre Brou N'Guessan Jean-Paul (Nanan Mougoh II), chef depuis 2014, accusé de lotissement illégal et vente de parcelles. Le chef dément et a porté plainte contre la mutuelle.",
    "status": "En cours",
    "observations": "Recoupe foncier et justice."
  },
  {
    "orderNumber": 28,
    "trackingId": "VEILLE-2026-028",
    "dateOfFacts": "08-09/05/2026",
    "source": "L'Expression n°4556",
    "region": "Région de l'Indénié-Djuablin",
    "locality": "Zamaka (Abengourou)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Après 15 ans d'incertitude et de blocages, intronisation de Nanan Kouakou Kouassi Nicolas à la tête de la tribu Ayoko-Kwabre.",
    "status": "Résolu",
    "observations": "Cas de référence pour la durée possible d'un blocage de succession."
  },
  {
    "orderNumber": 29,
    "trackingId": "VEILLE-2026-029",
    "dateOfFacts": "28/05/2026",
    "source": "Notre Voie n°7923",
    "region": "Région du Haut-Sassandra",
    "locality": "Issia",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Désignation consensuelle de deux représentants départementaux à la CNRCT (Pierre Michel Ipaud-Lago et Yoh Gama), après plusieurs séances de médiation, en remplacement de deux chefs décédés en 2025.",
    "status": "Résolu",
    "observations": ""
  },
  {
    "orderNumber": 30,
    "trackingId": "VEILLE-2026-030",
    "dateOfFacts": "29/04/2026 (verdict)",
    "source": "Soir Info n°9445",
    "region": "Région du Sud-Comoé",
    "locality": "Ebrah (Grand-Bassam)",
    "category": "Conflit",
    "conflictType": "Problème de justice",
    "description": "Verdict rendu le 29/04/2026, sept ans après les manifestations de 2019 déclenchées par la profanation d'un tam-tam sacré (Attoumgblan) à la veille d'une intronisation royale. 12 condamnés à 10-15 ans avec sursis et 100 millions FCFA d'amende ; 2 relaxés. Appel annoncé.",
    "status": "En cours (appel)",
    "observations": ""
  },
  {
    "orderNumber": 31,
    "trackingId": "VEILLE-2026-031",
    "dateOfFacts": "25/04/2026 (décès)",
    "source": "Soir Info n°9479",
    "region": "Région du Guémon",
    "locality": "Zéo (département de Bangolo)",
    "category": "Conflit",
    "conflictType": "Problème de justice",
    "description": "Séa Ferdinand, chef du village de Zéo, décédé le 25/04/2026 en prison où il purgeait 5 ans ferme, condamné après la mort en 2024 de l'instituteur Bomayé Luc Valène (ligoté et laissé sans assistance, soupçonné de vol). Domicile du chef incendié par les proches de la victime en 2024.",
    "status": "Clos (décès)",
    "observations": ""
  },
  {
    "orderNumber": 32,
    "trackingId": "VEILLE-2026-032",
    "dateOfFacts": "30/04/2026 (lettre ouverte)",
    "source": "L'Inter n°8344",
    "region": "Région du Guémon",
    "locality": "Duékoué",
    "category": "Conflit",
    "conflictType": "Problème de justice",
    "description": "Lettre ouverte d'Achille Dodé au Président de la République : reconnaissance des massacres commis contre le peuple Wê depuis 2002, enquêtes indépendantes, réparations, réconciliation, mécanismes de protection.",
    "status": "À suivre",
    "observations": ""
  },
  {
    "orderNumber": 33,
    "trackingId": "VEILLE-2026-033",
    "dateOfFacts": "25/06/2026",
    "source": "L'Intelligent n°5713",
    "region": "Région des Grands-Ponts",
    "locality": "Dabou / Lopou",
    "category": "Conflit",
    "conflictType": "Problème de justice",
    "description": "Le président du comité régional de la Chambre des rois et chefs, chef du village de Lopou (ancien ministre, 82 ans), dément des accusations de perception de 100 millions FCFA d'une société dans des conflits internes à la chefferie ; indique avoir porté plainte et obtenu des condamnations.",
    "status": "En cours",
    "observations": "Son nom n'apparaît pas explicitement dans la fiche source - à vérifier avant citation."
  },
  {
    "orderNumber": 34,
    "trackingId": "VEILLE-2026-034",
    "dateOfFacts": "28/06/2026 (réunion)",
    "source": "L'Expression n°4595 (09/07)",
    "region": "Région du Gontougo",
    "locality": "Kroupikro, N'Zuassé, Benanon, Sokoura N'Détiesso (Transua)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Réunion des chefs traditionnels le 28/06/2026 sur l'orpaillage illégal sévissant dans ces villages. Nanan Obeng Kouakou Ignace a mis en cause la responsabilité de certains chefs de village (complicité ou perte d'autorité). Rappel des voies légales d'exploitation.",
    "status": "En cours",
    "observations": ""
  },
  {
    "orderNumber": 35,
    "trackingId": "VEILLE-2026-035",
    "dateOfFacts": "22/06/2026 (réunion)",
    "source": "Fraternité Matin n°18437 (24/06)",
    "region": "Région du Gontougo",
    "locality": "Bondoukou",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Réunion de sensibilisation le 22/06/2026 à l'initiative du sous-préfet Sonh Laurent. Seulement 4 autorisations minières en règle dans la sous-préfecture. Cours d'eau ayant changé de couleur sous l'effet des exploitations clandestines. Renforcement annoncé des contrôles.",
    "status": "En cours",
    "observations": ""
  },
  {
    "orderNumber": 36,
    "trackingId": "VEILLE-2026-036",
    "dateOfFacts": "13/07/2026",
    "source": "Le Nouveau Réveil n°7142",
    "region": "Région du Worodougou",
    "locality": "Kouego (département de Séguéla)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Opération de déguerpissement du GSLOI dégénérée en affrontements avec des orpailleurs clandestins : plusieurs blessés, un décédé pendant son évacuation. Site dans le périmètre du permis de Roxgold Séguéla. Équipements de la compagnie vandalisés en représailles.",
    "status": "En cours",
    "observations": "Cas le plus grave du corpus en orpaillage (un mort)."
  },
  {
    "orderNumber": 36,
    "trackingId": "VEILLE-2026-036",
    "dateOfFacts": "13/07/2026 ; second raid 29/08",
    "source": "Le Nouveau Réveil n°7142 ; Soir Info n°9540 (03/09)",
    "region": "Région du Worodougou",
    "locality": "Kouego / Kouégo (sous-préfecture de Worofla, département de Séguéla)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Opération de déguerpissement du GSLOI du 13/07/2026 dégénérée en affrontements avec des orpailleurs clandestins : plusieurs blessés, un décédé pendant son évacuation ; équipements de la société Roxgold Séguéla vandalisés en représailles. Le site s'est reconstitué : le 29/08/2026, une nouvelle opération de l'Escadron de Séguéla, du GSLOI et de la brigade de Kani a permis l'interpellation de 3 individus en pleine activité, le démantèlement de deux bases logistiques et la destruction d'un matériel considérable (100 concasseurs, 107 bidons, 52 abris de fortune, 48 moulins, 32 rampes de lavage, 19 groupes électrogènes, 57 détonateurs électriques, 13 bâtons de dynamite, 3 bidons d'acide nitrique, entre autres).",
    "status": "En cours (site recolonisé puis re-démantelé)",
    "observations": "Cas le plus grave du corpus en orpaillage (un mort en juillet). La reconstitution du site deux mois après le premier raid illustre le problème de recolonisation évoqué au niveau national."
  },
  {
    "orderNumber": 37,
    "trackingId": "VEILLE-2026-037",
    "dateOfFacts": "25/06/2026",
    "source": "L'Inter n°8390 (29/06)",
    "region": "Région du Worodougou",
    "locality": "District du Woroba (étape Séguéla)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Tournée nationale de sensibilisation du ministre des Mines : le Worodougou concentrerait 60% des sites clandestins du district ; 80% des revenus de l'orpaillage illégal captés par des filières étrangères contre 7% pour les communautés locales. Plus de 800 autorisations artisanales délivrées en 3 ans.",
    "status": "En cours",
    "observations": "Trois semaines avant le drame de Kouego, dans le même département."
  },
  {
    "orderNumber": 38,
    "trackingId": "VEILLE-2026-038",
    "dateOfFacts": "26/04/2026",
    "source": "Soir Info n°9440 (29/04)",
    "region": "Région du Moronou",
    "locality": "Abongoua (Kotobi, département d'Arrah)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Deux enfants d'une même mère (13 et 15 ans) morts noyés le 26/04/2026 dans un puits abandonné par des orpailleurs clandestins sur le site « Agbonou », en tentant de se secourir mutuellement. Corps repêchés le lendemain.",
    "status": "Clos (drame)",
    "observations": "Second décès du corpus directement imputable à l'orpaillage illégal."
  },
  {
    "orderNumber": 39,
    "trackingId": "VEILLE-2026-039",
    "dateOfFacts": "08/07/2026 (tournée)",
    "source": "Soir Info n°9498 (10/07) ; L'Inter n°8404 (15/07)",
    "region": "Région du Sud-Comoé",
    "locality": "Kouakro (département d'Aboisso)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le préfet de région Ibrahima Cissé a averti que tout chef de village dont la complicité dans l'orpaillage clandestin serait établie serait immédiatement destitué. Dispositif d'investigation annoncé.",
    "status": "En cours",
    "observations": "Tournée à poursuivre à Maféré et Adjouan."
  },
  {
    "orderNumber": 40,
    "trackingId": "VEILLE-2026-040",
    "dateOfFacts": "08/07/2026",
    "source": "L'Inter n°8400 (10/07)",
    "region": "Région du Gôh",
    "locality": "Gagnoa (filière cacao)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le chef Diby Koffi Diby alerte que la mévente des stocks de cacao pousse les fils de planteurs vers l'orpaillage illégal faute d'argent, fixant un ultimatum au 07/08 pour l'enlèvement des stocks résiduels.",
    "status": "À suivre",
    "observations": "Lien causal direct entre crise cacaoère et orpaillage."
  },
  {
    "orderNumber": 41,
    "trackingId": "VEILLE-2026-041",
    "dateOfFacts": "23/04/2026",
    "source": "Notre Voie n°7896 (27/04)",
    "region": "Région du Cavally",
    "locality": "Parcs de Taï et du Cavally (Guiglo)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Les comités de gestion locaux des aires protégées ont identifié les pressions foncières et l'orpaillage clandestin comme principaux défis, avec recommandations de sensibilisation et de projets alternatifs générateurs de revenus.",
    "status": "À suivre",
    "observations": "Mention générale, pas un incident ponctuel."
  },
  {
    "orderNumber": 42,
    "trackingId": "VEILLE-2026-042",
    "dateOfFacts": "04/08/2026 (faits) ; interpellations 12/08 ; caravane 17-22/08",
    "source": "Fraternité Matin n°18475, n°18479 (14/08), n°18483",
    "region": "Région de La Mé",
    "locality": "Kossandji (sous-préfecture de Danguira, Alépé)",
    "category": "Conflit",
    "conflictType": "Affrontement intercommunautaire",
    "description": "Affrontement intercommunautaire entre allochtones et autochtones né d'un différend foncier autour d'une parcelle agricole familiale, survenu le 4 août 2026 à Kossandji : destruction de plants de manioc, altercation, puis saccage de magasins et boutiques. Bilan actualisé : 7 morts, plusieurs blessés et une personne portée disparue, dégâts matériels importants. Le 6 août, Patrick Achi (président du Conseil régional de La Mé) s'est rendu sur place au nom du Président Ouattara pour exprimer la compassion de l'État. Enquête judiciaire ouverte : 18 personnes interpellées, déférées devant le parquet le 12 août et placées sous mandat de dépôt par le procureur près le tribunal d'Abobo, Counta Nafissiatou, pour meurtre, troubles à l'ordre public, détention illégale d'armes à feu, association de malfaiteurs, vol en réunion et coups et blessures. Du 17 au 22 août, l'Union des chefs de village de Danguira a organisé une caravane de sensibilisation dans les 14 villages de la sous-préfecture.",
    "status": "En cours (procédure judiciaire ouverte)",
    "observations": "Cas le plus grave du corpus (7 morts, 18 interpellations). Recoupe foncier et justice."
  },
  {
    "orderNumber": 43,
    "trackingId": "VEILLE-2026-043",
    "dateOfFacts": "24/07/2026 (interpellation)",
    "source": "Notre Voie n°7962 (03/08)",
    "region": "Région du Guémon",
    "locality": "Canton Zarabaon (département de Bangolo)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "La jeunesse du département de Bangolo dénonce la prolifération de barrages routiers illégaux (31 recensés entre Bangolo et Zérégbo) tenus par des forces de l'ordre venues de Man ou Duékoué, avec des taxes de 500 à 2000 FCFA répercutées sur les usagers. Elle dénonce aussi l'occupation des terres par des populations allogènes, plaidant pour leur insertion économique plutôt que leur exclusion. Le préfet a appelé à la patience et promis de transmettre les préoccupations à Abidjan.",
    "status": "À suivre",
    "observations": "Mention foncière générale, associée à une problématique de racket aux barrages."
  },
  {
    "orderNumber": 44,
    "trackingId": "VEILLE-2026-044",
    "dateOfFacts": "29/07/2026 (rencontre)",
    "source": "Le Rassemblement n°1980 (06/08)",
    "region": "Région du Guémon",
    "locality": "Nidrou (département de Duékoué)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Rencontre de sensibilisation organisée par l'ONG « Le Citoyen Nouveau » sur la sécurisation du foncier rural (rôle de l'AFOR, certificat foncier), quelques mois après des affrontements meurtriers dans le village voisin de Bagohouo. Le directeur régional de l'AFOR a présenté le certificat foncier comme un levier essentiel de prévention des conflits.",
    "status": "À suivre",
    "observations": "Référence un incident antérieur à Bagohouo non documenté dans nos fiches précédentes — à vérifier si signalé dans une revue manquante."
  },
  {
    "orderNumber": 45,
    "trackingId": "VEILLE-2026-045",
    "dateOfFacts": "29/07/2026",
    "source": "Fraternité Matin n°18474 (06/08)",
    "region": "Région de La Mé",
    "locality": "Akoupé",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "La jeunesse du département d'Akoupé a exprimé un refus catégorique de toute activité d'orpaillage sur son territoire, invoquant la protection des terres agricoles et des rivières. Sollicitation des autorités politiques, administratives et coutumières pour préserver la vocation agricole du département.",
    "status": "À suivre",
    "observations": ""
  },
  {
    "orderNumber": 46,
    "trackingId": "VEILLE-2026-046",
    "dateOfFacts": "01/08/2026 (constitution du RECAK)",
    "source": "L'Avenir n°1515 (10/08)",
    "region": "Région du Bélier",
    "locality": "Kokumbo",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Constitution du Réseau des Cadres de Kokumbo (RECAK, général Athanase Yao N'Dri à sa tête). La sous-préfète Goué Rosine Prisca a alerté sur les ravages de l'orpaillage clandestin dans la localité : explosion des échecs et abandons scolaires, incivilité croissante, perte des repères civiques chez les jeunes. L'accession de la sous-préfecture au statut de département est présentée comme conditionnée à l'éradication du phénomène.",
    "status": "En cours",
    "observations": ""
  },
  {
    "orderNumber": 47,
    "trackingId": "VEILLE-2026-047",
    "dateOfFacts": "13/08/2026 (déclaration)",
    "source": "Le Nouveau Réveil n°7165 (13/08)",
    "region": "Portée nationale",
    "locality": "Trois villages non identifiés",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le ministre de l'Environnement Abou Bamba met en avant l'exemple de trois villages ayant choisi de préserver leurs terres et forêts plutôt que de céder à l'orpaillage clandestin, rappelant qu'aucun orpailleur ne peut opérer sans l'autorisation des chefs de communauté. Il souhaite dupliquer ce modèle de conservation communautaire à l'échelle nationale.",
    "status": "À suivre",
    "observations": "Localités non nommées dans l'article."
  },
  {
    "orderNumber": 48,
    "trackingId": "VEILLE-2026-048",
    "dateOfFacts": "20/08/2026 (publication)",
    "source": "Notre Voie n°7974 (20/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (analyse méthodologique)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Un document de la Direction générale des Mines et de la Géologie reconstitue le mode opératoire des réseaux d'orpaillage clandestin : approche discrète des propriétaires terriens, tests, négociation élargie à la communauté (parts de production pour obtenir un « silence collectif »), neutralisation des contrôles par corruption, puis installation du site et arrivée de criminalité connexe (trafic, stupéfiants, armes). L'institution souligne que tout part de l'accès à la terre et appelle les communautés à refuser dès la première sollicitation.",
    "status": "À suivre",
    "observations": "Document méthodologique national, pas un incident localisé."
  },
  {
    "orderNumber": 49,
    "trackingId": "VEILLE-2026-049",
    "dateOfFacts": "06-27/08/2026 (opérations en cours)",
    "source": "Le Matin n°2094 (27/08)",
    "region": "Portée nationale (Bagoué, Poro, Bounkani, Moronou, Iffou, Agnéby-Tiassa, Bélier, Nawa, Grand-Zattry, Maféré, Aboisso, Marahoué, Daoukro, Séguéla, Zaguinasso)",
    "locality": "Multi-localités",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le GSLOI intensifie ses opérations sur l'ensemble du territoire (déclaration du général Alexandre Apalo Touré à Soubré). Le phénomène touche désormais quasiment toutes les régions, avec des réseaux de plus en plus structurés (excavatrices, produits chimiques) ; la part des Ivoiriens parmi les personnes arrêtées serait passée de 10 % à 30 %. Opérations récentes : 32 interpellations et 40 pelleteuses saisies en Marahoué (48h de traque, 6 sites détruits) ; 3 porte-chars, 2 bulldozers et 350 motopompes neutralisés à Daoukro ; opérations à Séguéla et Zaguinasso ; usage de drones à la frontière malienne.",
    "status": "En cours",
    "observations": "Vue d'ensemble nationale utile pour contextualiser les cas locaux déjà recensés (Kouego, Transua, Bondoukou, etc.)."
  },
  {
    "orderNumber": 50,
    "trackingId": "VEILLE-2026-050",
    "dateOfFacts": "Enquête mars 2022 (rapport republié en 08/2026)",
    "source": "L'Avenir n°1528 (27/08)",
    "region": "Portée nationale (30 régions sur 31, hors Abidjan)",
    "locality": "Non localisé (rapport statistique)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Rapport du CNDH (sous la présidence de Namizata Sangaré) : 70 % des sites d'orpaillage recensés en mars 2022 étaient clandestins (252 sur 360). Quatre régions concentraient l'essentiel des sites clandestins : Hambol (45, 17,86 %), Moronou (26, 10,32 %), La Mé (23, 9,13 %) et Bagoué (20, 7,94 %). Population d'orpailleurs estimée à 23 400 individus. Pertes pour l'État entre 2006 et 2016 estimées à 479,22 milliards FCFA. Sites parfois protégés par des sociétés de sécurité privée, d'ex-démobilisés, des dozos, voire des forces de l'ordre (Tabou).",
    "status": "Clos (rapport historique 2022)",
    "observations": "Rapport ancien remis en avant dans le contexte de la lutte anti-orpaillage d'août 2026 ; chiffres à dater précisément avant réemploi (enquête de 2022)."
  },
  {
    "orderNumber": 51,
    "trackingId": "VEILLE-2026-051",
    "dateOfFacts": "21/08/2026 (présentation)",
    "source": "L'Inter n°8437 (27/08)",
    "region": "District Autonome d'Abidjan",
    "locality": "Éloka-Tô (Bingerville)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Jean Daniel Agoua Agoua (54 ans, adjudant-chef de police, ex-directeur de cabinet du regretté chef Mobio Adja Jean-Philippe) a été présenté le 21/08/2026 à la communauté comme nouveau chef du village. Étape suivante : consultation populaire sollicitée auprès du sous-préfet, avant installation officielle.",
    "status": "En cours",
    "observations": "Suite du dossier Éloka-Tô déjà recensé (usurpation par Akosso Abé Jacob, incarcéré depuis mai 2026 ; Mobio Adja Jean-Philippe reconnu chef en 2021, depuis décédé)."
  },
  {
    "orderNumber": 52,
    "trackingId": "VEILLE-2026-052",
    "dateOfFacts": "26/08/2026 (sit-in) ; négociation 31/08",
    "source": "L'Inter n°8437 (27/08), n°8441 (01/09)",
    "region": "District Autonome d'Abidjan",
    "locality": "M'Badon (Cocody)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Sit-in organisé le 26/08/2026 par la communauté de M'Badon contre la vente d'une parcelle de 7 275 m² prélevée sur le cimetière coutumier du village par Laetitia Amangou, héritière de feu Victor Amangou. Le 31/08, la préfecture d'Abidjan a organisé une rencontre entre la chefferie et Mme Amangou : le secrétaire général de préfecture a confirmé que celle-ci détient une attestation villageoise de 1986 signée par l'ancien chef Benié Samuel, ayant abouti à un arrêté de concession définitive (ACD), et a invité les deux parties à négocier plutôt qu'à s'affronter, précisant qu'en cas d'échec l'affaire irait devant le Conseil d'État, la charge de la preuve en cas d'accusation de fraude revenant à l'accusateur. La chefferie (porte-parole Loba Alexandre) rappelle que Mme Amangou avait été convoquée cinq ans plus tôt sans se présenter ; celle-ci se dit désormais disposée à discuter.",
    "status": "En cours (négociation engagée)",
    "observations": "La documentation officielle de la vendeuse (ACD) fragilise la position initiale de la chefferie ; issue incertaine entre négociation et saisine du Conseil d'État."
  },
  {
    "orderNumber": 53,
    "trackingId": "VEILLE-2026-053",
    "dateOfFacts": "21/08/2026 (séance)",
    "source": "Le Nouveau Réveil n°7174 (27/08)",
    "region": "Région du Cavally",
    "locality": "Toulepleu",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Séance d'information et de sensibilisation sur la lutte contre l'orpaillage illégal tenue le 21/08/2026 sous la présidence du préfet Bini Koffi Étienne, dans le cadre des préparatifs de l'Atelier national de concertation et d'harmonisation initié par le Conseil national de sécurité (CNS). La jeunesse locale a réaffirmé sa volonté de s'impliquer dans la sensibilisation et la préservation des ressources naturelles.",
    "status": "À suivre",
    "observations": ""
  },
  {
    "orderNumber": 54,
    "trackingId": "VEILLE-2026-054",
    "dateOfFacts": "Depuis 10/08/2026 (blocage) ; faits 2024",
    "source": "Le Jour Plus n°5900 (17/08)",
    "region": "À vérifier (Lôh-Djiboua)",
    "locality": "Ditola (site aurifère, proche de Hiré)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Blocage du site aurifère de Ditola depuis le 10/08/2026 à l'initiative de l'ancien chef intérimaire Nanan Christophe Komenan, soutenu par les chefs de terre et la jeunesse, en réaction à l'incarcération depuis 2024 de Jérémie Gnamini et cinq autres jeunes du village. Origine : différend de parrainage sur un agrément d'extraction d'or entre ce groupe de jeunes et la société minière Allied Gold. L'ancien chef affirme qu'une enquête a écarté l'orpaillage illégal et dénonce le licenciement d'une vingtaine de jeunes en violation d'une convention d'emploi prioritaire des fils de Hiré. Il exige la libération des six détenus et maintient le blocage. L'épouse d'un détenu a appelé à la clémence du Président de la République.",
    "status": "En cours",
    "observations": "Dispute avec une société minière légale (Allied Gold), distincte de l'orpaillage clandestin proprement dit. Recoupe justice (détention depuis 2 ans) et foncier (droits de parrainage/emploi local)."
  },
  {
    "orderNumber": 55,
    "trackingId": "VEILLE-2026-055",
    "dateOfFacts": "12/08/2026 (démolitions) ; 19/08 (sursis) ; 03/09 (nouvel acteur)",
    "source": "Le Jour n°5905 (24/08) ; Le Nouveau Réveil n°7183 (09/09)",
    "region": "District Autonome d'Abidjan",
    "locality": "4 Croix (commune d'Anyama)",
    "category": "Conflit",
    "conflictType": "Foncier",
    "description": "Litige foncier entre les populations du village de 4 Croix et la société Arc-en-ciel. Démolitions le 12/08/2026 de plus de 30 constructions dont une école ; le 19/08, le chef du village a obtenu un sursis à exécution devant la Cour de cassation. Le dossier s'est complexifié le 03/09/2026 avec l'intervention de l'entreprise ESTP et de sa partenaire financière Ouattara Awa, dans un différend distinct portant sur 72 hectares du même site : l'ESTP affirme avoir investi 1,79 milliard FCFA en cinq ans avant l'arrêt des travaux imposé par un opérateur revendiquant la propriété du domaine. Elle dénonce des lots vendus sous ses sceaux sans respect des accords, ainsi qu'une vente présumée de plus de 2 000 lots à la CNPS et à la CGRAE sans information des propriétaires coutumiers, qu'elle qualifie de faux et escroquerie. Une plainte a été déposée devant le Pôle pénal économique et financier.",
    "status": "En cours (deux procédures parallèles)",
    "observations": "Dossier foncier désormais à plusieurs strates : village vs Arc-en-ciel (procédure judiciaire en cours) et ESTP vs opérateur tiers (plainte pénale distincte) sur le même site."
  },
  {
    "orderNumber": 56,
    "trackingId": "VEILLE-2026-056",
    "dateOfFacts": "06-11/08/2026 (analyses publiées)",
    "source": "Le Nouveau Réveil n°7163 (11/08)",
    "region": "Portée nationale",
    "locality": "Agboville (exemple cité) et ensemble du territoire",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Trois textes d'opinion publiés après le message à la Nation du Président Ouattara du 6/08/2026, qui n'avait pas abordé l'orpaillage malgré une demande antérieure de renforcement de la lutte au Conseil national de sécurité. Un texte relaie une alerte de la SODECI établissant un lien entre orpaillage clandestin, usage de mercure et coupures d'eau touchant des milliers de familles ; à Agboville, l'eau du robinet a été interdite à la consommation après une coloration ocre attribuée à la pollution minière. Un autre rappelle qu'en 2019 le phénomène touchait 12 régions sur 31, contre 29 aujourd'hui selon l'auteur.",
    "status": "En cours",
    "observations": "Illustre l'impact concret de l'orpaillage sur l'accès à l'eau potable (cas documenté d'Agboville)."
  },
  {
    "orderNumber": 57,
    "trackingId": "VEILLE-2026-057",
    "dateOfFacts": "24/08/2026 (déclaration)",
    "source": "Le Matin n°2092 (24/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (déclaration institutionnelle)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le général Apalo Touré a annoncé une intensification de la lutte contre l'orpaillage illégal, ciblant désormais explicitement les complicités : toute connivence avérée d'un agent avec des orpailleurs entraînera une radiation sans possibilité de pardon. Il a qualifié les atteintes aux barrages hydroélectriques par les activités clandestines d'atteinte à la sécurité de l'État, au même titre que la pollution des cours d'eau.",
    "status": "En cours",
    "observations": "Complète le dossier GSLOI déjà recensé (opérations du 27/08)."
  },
  {
    "orderNumber": 58,
    "trackingId": "VEILLE-2026-058",
    "dateOfFacts": "21/08/2026 (journée de sensibilisation)",
    "source": "L'Inter n°8435 (24/08)",
    "region": "Région du Tchologo",
    "locality": "Diawala",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Journée de sensibilisation organisée à l'invitation du sous-préfet avec la Fédération des coopératives minières de Côte d'Ivoire (FECOMCI), pour inciter jeunes et exploitants à se constituer en coopératives afin de sortir de l'illégalité. Le président de la FECOMCI a rappelé que ce statut ne donne pas automatiquement droit d'exploiter et ne remplace aucune autorisation de l'État. La localité compte déjà 17 coopératives minières légalement constituées ; deux demandes de permis minier ont été remises lors de la rencontre.",
    "status": "En cours",
    "observations": ""
  },
  {
    "orderNumber": 59,
    "trackingId": "VEILLE-2026-059",
    "dateOfFacts": "20/08/2026 (rencontre)",
    "source": "Fraternité Matin n°18486 (24/08)",
    "region": "Région du Tonkpi",
    "locality": "Danané",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Rencontre de sensibilisation à la préfecture organisée par le directeur départemental des Mines, appelant les chefs de village à informer leurs populations, signaler toute présence douteuse et s'abstenir de tout contact avec les orpailleurs, et les propriétaires terriens à ne pas mettre leurs terres à disposition des exploitants clandestins. Alternative légale présentée (délai de traitement des autorisations : trois mois, exemple d'un opérateur du village de Seipleu). Les chefs traditionnels ont demandé des mesures fermes contre les auteurs et leurs complices.",
    "status": "En cours",
    "observations": ""
  },
  {
    "orderNumber": 60,
    "trackingId": "VEILLE-2026-060",
    "dateOfFacts": "23/07/2026 (annonce CNS) ; texte du 31/08",
    "source": "Le Jour n°5909 (31/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (analyse d'opinion)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Un texte d'opinion demande un bilan à mi-parcours de la dynamique nationale de lutte contre l'orpaillage lancée après les révélations du Conseil national de sécurité du 23/07/2026, pour répondre aux interrogations circulant dans la population : détention effective des orpailleurs arrêtés ou libérations discrètes contre paiement, surveillance des sites déguerpis contre leur recolonisation, ciblage réel des complices locaux protégés par des personnalités influentes, devenir de l'or et de l'argent saisis.",
    "status": "À suivre",
    "observations": "Reflète une défiance de l'opinion envers l'effectivité du dispositif de lutte."
  },
  {
    "orderNumber": 61,
    "trackingId": "VEILLE-2026-061",
    "dateOfFacts": "4-5/09/2026 (atelier tenu)",
    "source": "Le Matin n°2101 (04/09) ; Le Jour Plus n°5914, Le Patriote n°7986 (08/09)",
    "region": "Portée nationale",
    "locality": "Yamoussoukro",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "L'atelier national d'harmonisation des mécanismes de lutte contre l'orpaillage illégal, initié par le Conseil national de sécurité (CNS), s'est tenu les 4 et 5 septembre 2026 à Yamoussoukro, réunissant corps préfectoral, chefferie traditionnelle (Chambre nationale des rois et chefs traditionnels) et guides religieux. Le phénomène représenterait environ 40 tonnes d'or échappant chaque année au circuit légal, soit près de 3 000 milliards FCFA. Le ministre de l'Intérieur, général Vagondo Diomandé, a annoncé une intensification de la répression et réaffirmé la « tolérance zéro » face à toute complicité, avec un rôle central confié aux préfets. Le secrétaire exécutif du CNS, Fidèle Sarassoro, a présenté un bilan (juillet 2021-juillet 2026) de plus de 1 000 sites démantelés en 8 500 opérations, 4 665 personnes déférées, 136 kg d'or saisis, pour un investissement de l'État de plus de 15 milliards FCFA, tout en mettant en garde contre l'autosatisfaction. Le président de la CNRCT, Sa Majesté Amon Tanoe Désiré, a déclaré à Aboisso : « En tant que gardiens des terres, des eaux et des ressources naturelles, nous avons une responsabilité de protéger ces ressources. »",
    "status": "En cours (recommandations attendues)",
    "observations": "Implique directement la CNRCT à travers la prise de parole publique de son président. Un éditorial du 08/09 (Le Nouveau Réveil) qualifie cet atelier d'aveu implicite d'échec des dispositifs antérieurs, faute d'anticipation depuis l'alerte de 2013."
  },
  {
    "orderNumber": 62,
    "trackingId": "VEILLE-2026-062",
    "dateOfFacts": "01/08/2026",
    "source": "Fraternité Matin n°18473 (05/08)",
    "region": "Région des Grands-Ponts",
    "locality": "Cosrou (village d'Ira, département de Dabou)",
    "category": "Conflit",
    "conflictType": "Problème de justice",
    "description": "Akpa Michel, 75 ans, patriarche du village de Cosrou, a été assassiné à l'arme blanche le 1er août 2026 dans sa plantation d'hévéa, le cou brisé, une branche taillée plantée dans la gorge. Ni les fonds de tasse, ni le téléphone, ni l'argent qu'il portait n'ont été dérobés, écartant la piste du vol classique. Les soupçons se portent sur deux de ses fils, introuvables depuis le drame. Un différend ancien remontant à près d'une décennie entre le patriarche et sa deuxième épouse est évoqué sans que le lien avec le crime soit établi.",
    "status": "En cours",
    "observations": "Enquête en cours ; mobile familial non confirmé à ce stade."
  },
  {
    "orderNumber": 63,
    "trackingId": "VEILLE-2026-063",
    "dateOfFacts": "12/05/2026 (annonce) ; incohérence chronologique relevée",
    "source": "L'Avenir n°1519 (14/08)",
    "region": "District Autonome d'Abidjan",
    "locality": "Anonkoua-Kouté (commune d'Abobo)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Le Conseil des anciens a destitué Sokoi Aloucou Clément de ses fonctions de chef du village, invoquant une gestion opaque du patrimoine foncier villageois : cession d'une parcelle de deux hectares derrière le Lycée municipal d'Abobo avec versements financiers importants sans information ni autorisation de la communauté, décisions prises sans consultation des doyens et générations. Inquiétudes également sur des opérations foncières à Abbébroukoi 2 portant sur plusieurs centaines de lots. La communauté exige son remplacement immédiat.",
    "status": "En cours",
    "observations": "Le texte source présente une incohérence chronologique (annonce datée du 12 mai, destitution effective au 15 mai). Recoupe foncier."
  },
  {
    "orderNumber": 64,
    "trackingId": "VEILLE-2026-064",
    "dateOfFacts": "Phénomène en cours (reportage août 2026)",
    "source": "Le Patriote n°7965 (12/08)",
    "region": "Région de l'Iffou",
    "locality": "Koutoukounou (près de Daoukro) et département de Daoukro, M'Bahiakro, Ouellé, Prikro",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Reportage décrivant l'ampleur de l'orpaillage illégal dans les quatre départements de l'Iffou, amplifié depuis 2010 : sites creusés jusqu'à plus de sept mètres de profondeur rendant les terres impropres à l'agriculture pour des décennies, plantations de café détruites. Un notable témoigne de conflits fonciers récurrents entre familles, la chefferie étant tenue à l'écart des arrangements passés entre orpailleurs et propriétaires terriens ; complicité de certains chefs de village évoquée par des habitants. Bilan : déforestation massive, pollution au mercure et au cyanure, trafics de drogue, d'armes et de personnes, déscolarisation, insécurité. Un notable de Prikro appelle à une intervention de l'armée.",
    "status": "En cours",
    "observations": "Recoupe foncier (conflits entre familles) et désignation des chefs (complicité alléguée)."
  },
  {
    "orderNumber": 65,
    "trackingId": "VEILLE-2026-065",
    "dateOfFacts": "01/01-31/07/2026 (bilan)",
    "source": "Le Rassemblement n°1987 (18/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (bilan statistique gendarmerie)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Bilan de la gendarmerie nationale (GSLOI) : 1 114 sites d'orpaillage illégal déguerpis et 1 531 personnes interpellées entre le 1er janvier et le 31 juillet 2026. Saisies : 4 410,42 grammes d'or, 244 groupes électrogènes, 255 barres de dynamite, 2 541 motopompes. Destructions : 16 200 abris de fortune, 169 broyeuses, 6 142 motopompes, 5 845 concasseurs.",
    "status": "En cours",
    "observations": "Statistiques à recouper avec le bilan CNS déjà recensé (autre source, chiffres proches mais non identiques)."
  },
  {
    "orderNumber": 66,
    "trackingId": "VEILLE-2026-066",
    "dateOfFacts": "15-16/08/2026 ; détails 04/09",
    "source": "Fraternité Matin n°18481 (18/08) ; L'Avenir n°1535 (04/09)",
    "region": "Portée nationale",
    "locality": "Gbémou, Sissèdougou (Boundiali), Andé (Moronou)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le directeur général des Mines a cité Gbémou, Sissèdougou et Andé comme localités ayant empêché l'implantation de l'orpaillage clandestin grâce à des cellules de veille communautaires. Un article du 04/09 précise le mécanisme : à Gbémou, le village a refusé de sacrifier un barrage agricole face au premier intermédiaire venu tâter le terrain ; selon l'analyse, la différence ne tient ni à la géologie ni au nombre de gendarmes mais à la réponse donnée collectivement dès la première sollicitation. Par contraste, la région du Béré compte quinze sites illégaux et le Tchologo une vingtaine. Statistiques nationales rappelées : 1 114 sites déguerpis par la gendarmerie entre janvier et juillet 2026 ; plus de 8 500 sites démantelés et 4 474 personnes déférées (65 % d'étrangers) depuis 2021 ; plus de 800 autorisations d'exploitation artisanale délivrées en trois ans. Un site détruit peut toutefois rouvrir dès le départ de la patrouille si personne localement ne s'y oppose.",
    "status": "Résolu (localement) / En cours (national)",
    "observations": "Cas positifs érigés en modèle national ; illustre par contraste le risque de recolonisation documenté ailleurs (Kouégo)."
  },
  {
    "orderNumber": 67,
    "trackingId": "VEILLE-2026-067",
    "dateOfFacts": "Bilan 2021 - mi-2026 (présenté le 23/07, republié 14/08 et 26/08)",
    "source": "Le Nouveau Réveil n°7166 (14/08) ; Le Matin n°2026 (26/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (bilan CNS)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Bilan du Conseil national de sécurité (CNS) sur la lutte contre l'orpaillage illégal, présenté le 23 juillet 2026 et largement relayé : plus de 8 500 sites clandestins démantelés, 4 474 individus déférés devant la justice (dont 65 % de ressortissants étrangers), environ 500 000 orpailleurs actifs dans 27 des 31 régions du pays, 136 kg d'or saisis et plus de 960 millions FCFA récupérés. Dans le Sud-Comoé, 31 sites ont été identifiés et déguerpis, notamment dans l'Affema (Maféré). Opérations citées : Zievasso (Odienné, 5 interpellations), bassin du fleuve Bandama en Marahoué (Bosoco, Panguacro), Iffou, N'zi, Moronou. Volet environnemental : réhabilitation prévue de 4 500 hectares via l'Abidjan Legacy Program.",
    "status": "En cours",
    "observations": "Bilan national de référence, agrégeant plusieurs opérations locales déjà recensées séparément dans ce tableau (Marahoué, Iffou, etc.)."
  },
  {
    "orderNumber": 68,
    "trackingId": "VEILLE-2026-068",
    "dateOfFacts": "19/08/2026 (réunion)",
    "source": "L'Intelligent n°5746 (21/08)",
    "region": "Région du Cavally",
    "locality": "Taï (zones de Zahipobly, Gahably, forêt classée de Goin-Débé près de Zagné)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le préfet de Taï a appelé, le 19 août 2026, à une mobilisation générale contre l'orpaillage illégal, alertant sur la pollution du fleuve Cavally qui empêcherait déjà la consommation du poisson et de l'eau dans certains villages. Plus de 25 sites clandestins recensés dans le département, dont le site du « Camp Blanc » qui abriterait plus de 500 orpailleurs utilisant mercure, cyanure et équipements lourds, aucun sans autorisation officielle selon la Direction des Mines de Guiglo. Recommandations : drone de surveillance, renforcement du contrôle frontalier et du fleuve, suivi des flux migratoires.",
    "status": "En cours",
    "observations": "Nouvel épisode du dossier Goin-Débé/Cavally déjà largement documenté ; ici sous l'angle spécifique de l'orpaillage et de la pollution du fleuve."
  },
  {
    "orderNumber": 69,
    "trackingId": "VEILLE-2026-069",
    "dateOfFacts": "Analyse publiée le 21/08 (données de juin 2026)",
    "source": "Le Nouveau Réveil n°7171 (21/08)",
    "region": "Portée nationale",
    "locality": "Non localisé (analyse d'opinion)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Un texte d'opinion alerte sur la multiplication des demandes d'enquêtes de commodo et d'incommodo pour l'exploitation aurifère : 24 demandes portant sur 2 021 hectares enregistrées au seul mois de juin 2026. L'auteur met en garde contre le risque qu'une délivrance massive d'autorisations serve à légaliser en apparence des pratiques inchangées et nuisibles, et réclame une suspension temporaire des nouvelles autorisations le temps de vérifier les antécédents des bénéficiaires, cartographier les sites et évaluer les impacts environnementaux et sociaux.",
    "status": "À suivre",
    "observations": "Tension entre la politique de formalisation (coopératives, permis) et le risque de légalisation de façade, déjà entrevue dans plusieurs dossiers recensés (Gagnoa, Diawala)."
  },
  {
    "orderNumber": 70,
    "trackingId": "VEILLE-2026-070",
    "dateOfFacts": "29/08/2026 (désignation)",
    "source": "Soir Info n°9538 (01/09 et 02/09)",
    "region": "Région du Guémon",
    "locality": "Guéhouo-Zagna (département de Bangolo)",
    "category": "Conflit",
    "conflictType": "Désignation des chefs",
    "description": "Trois ans après le décès du chef Tohé Blaise, les tentatives de succession avaient échoué face à la division des populations entre trois candidats. Le 29/08/2026, jour du vote des onze chefs de famille sous supervision d'une délégation de la Chambre des rois du Guémon et sécurisation de la gendarmerie, des jeunes réclamant une élection ouverte à toute la population ont bloqué les accès du village, refoulant gendarmes et délégation. Après une réunion de crise, le vote a finalement eu lieu : Zouhou Emile Arnaud a été désigné chef par les onze chefs de famille.",
    "status": "Résolu",
    "observations": "Tension réelle le jour même (blocage, refoulement des autorités) mais dénouement pacifique et rapide."
  },
  {
    "orderNumber": 71,
    "trackingId": "VEILLE-2026-071",
    "dateOfFacts": "13/07-14/08/2026 (campagne) ; menace 07/09",
    "source": "Le Nouveau Réveil n°7178 (02/09) ; Fraternité Matin n°18499 (09/09)",
    "region": "Région du Béré",
    "locality": "Département de Mankono et région du Béré",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Campagne de sensibilisation menée du 13 juillet au 14 août 2026 dans les trois départements du Béré (plus de 1 200 participants), révélant une ampleur préoccupante de l'orpaillage illégal, nourri par la pauvreté rurale et une complicité présumée de certaines autorités coutumières et administratives. Le prix de l'or est passé de 3 000-12 000 FCFA le gramme dans les années 2000 à 60 000-77 000 FCFA aujourd'hui, mais les populations locales n'en retireraient que 7 % des revenus contre 81 % pour des opérateurs souvent étrangers. Perte nationale estimée à 142 tonnes d'or et 744 milliards FCFA de recettes fiscales. Le 7 septembre, le préfet Boni Kouakou Adolphe a averti qu'il suspendrait les arrêtés de tout chef de village complice d'orpailleurs, rappelant que la pollution empêche désormais la SODECI de fournir l'eau potable dans certaines localités.",
    "status": "En cours",
    "observations": "Menace explicite de destitution administrative des chefs complices, dans la ligne du séminaire national de Yamoussoukro."
  },
  {
    "orderNumber": 72,
    "trackingId": "VEILLE-2026-072",
    "dateOfFacts": "03-04/09/2026 (caravane, 5e étape)",
    "source": "Le Nouveau Réveil n°7179 (03/09) ; L'Inter n°8444 (04/09)",
    "region": "Région du Sud-Comoé",
    "locality": "Aboisso",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Cinquième étape d'une campagne nationale de sensibilisation contre l'orpaillage illégal, lancée le 8 décembre 2023 à Yamoussoukro auprès du Directoire de la Chambre nationale des rois et chefs traditionnels (CNRCT). Le ministre des Mines, Mamadou Sangafowa Coulibaly, a salué une « prise de conscience collective », présentant les coopératives minières comme alternative crédible. Le directeur général des Mines a dressé un état des lieux national : en février 2026, 31 sites illégaux identifiés et déguerpis par le GSLOI et la BRICM ; pertes nationales de 142 tonnes d'or, soit plus de 4 600 milliards FCFA, dont 744 milliards FCFA de recettes fiscales échappant à l'État.",
    "status": "En cours",
    "observations": "Confirme que la campagne nationale de sensibilisation a été lancée en 2023 directement auprès de la CNRCT, avant même l'intensification de 2026."
  },
  {
    "orderNumber": 73,
    "trackingId": "VEILLE-2026-073",
    "dateOfFacts": "03/09/2026",
    "source": "Le Patriote n°7983 (04/09)",
    "region": "Région du Cavally",
    "locality": "Toulepleu",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "La ministre d'État Anne Désirée Ouloto-Lamizana, présidente du Conseil régional du Cavally, a réuni les chefs traditionnels de Toulepleu pour saluer les avancées d'infrastructures du département (bitumage, pont sur le Cavally) tout en les exhortant à s'impliquer contre l'orpaillage illégal, qualifiant cet argent de « malédiction » pour les terres et les familles.",
    "status": "À suivre",
    "observations": "Complète le dossier Toulepleu déjà recensé (séance de sensibilisation du 21/08)."
  },
  {
    "orderNumber": 74,
    "trackingId": "VEILLE-2026-074",
    "dateOfFacts": "31/08/2026",
    "source": "L'Inter n°8443 (03/09)",
    "region": "Région de la Nawa",
    "locality": "Buyo",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le directeur régional des Mines et de la Géologie de la Nawa a échangé avec les populations de Buyo sur les dangers de l'orpaillage illégal, en présence du préfet et de plusieurs chefs de village, appelant à dénoncer les exploitants clandestins qui abandonnent des terrains dégradés. Il a cité en exemple le village de Petigoa 2, qui bénéficie d'infrastructures sociales grâce à l'exploitant légal Metal Jaune (don prochain d'une ambulance).",
    "status": "À suivre",
    "observations": "Modèle positif d'exploitation légale mis en avant, à l'image de Gbémou/Sissèdougou."
  },
  {
    "orderNumber": 75,
    "trackingId": "VEILLE-2026-075",
    "dateOfFacts": "03/09/2026 (entretien)",
    "source": "Le Nouveau Réveil n°7179 (03/09)",
    "region": "Région du N'zi",
    "locality": "N'zi (ensemble de la région)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le Dr Emil Kouassi (Bureau politique du PDCI-RDA) qualifie le N'zi de région « naufragée » par l'orpaillage illégal, proposant le retrait de tous les agréments d'extraction et interpellant l'État sur la présence de préfets et forces de l'ordre censés contrôler le territoire. Il attribue la présence massive de jeunes sur les sites au chômage et au désespoir plutôt qu'à l'attrait de l'or, et se dit sceptique sur la capacité de l'usine UTEXI de Dimbokro, régulièrement annoncée avant chaque échéance électorale, à absorber cette jeunesse désœuvrée.",
    "status": "À suivre",
    "observations": "Critique politique (PDCI-RDA, parti d'opposition) de la gestion gouvernementale du dossier."
  },
  {
    "orderNumber": 76,
    "trackingId": "VEILLE-2026-076",
    "dateOfFacts": "09/09/2026",
    "source": "Fraternité Matin n°18499 (09/09)",
    "region": "Région de l'Iffou",
    "locality": "Ouellé",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Pour lutter contre l'orpaillage illégal par l'occupation permanente des terres, le maire de Ouellé, Ya Komenan Raphaël, offre aux jeunes et femmes de la commune des centaines d'hectares de plants de cultures pérennes : 250 ha de café, 100 ha d'hévéa, 100 ha de palmier à huile, en misant sur la sensibilisation des chefs de terre.",
    "status": "À suivre",
    "observations": "Initiative locale s'inscrivant dans le dossier plus large de l'orpaillage dans l'Iffou déjà recensé (reportage de Koutoukounou)."
  },
  {
    "orderNumber": 77,
    "trackingId": "VEILLE-2026-077",
    "dateOfFacts": "06/09/2026",
    "source": "Le Matin n°2105 (09/09)",
    "region": "Région du Haut-Sassandra",
    "locality": "Issia",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le ministre des Eaux et Forêts, Jacques Assahoré Konan, a réaffirmé devant ses agents à Issia la ligne de « tolérance zéro face à l'orpaillage illégal et au sciage à façon », leur demandant rigueur et intégrité sans complaisance.",
    "status": "À suivre",
    "observations": ""
  },
  {
    "orderNumber": 78,
    "trackingId": "VEILLE-2026-078",
    "dateOfFacts": "07/09/2026 (opération)",
    "source": "Le Mandat n°4411 (09/09)",
    "region": "Région du Belier",
    "locality": "Kahankro (commune de Toumodi)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Opération « Filet Vert du Nord » menée par la Brigade spéciale de surveillance et d'intervention (BSSI) : 16 individus interpellés et mis à disposition de la justice pour infractions aux codes minier, forestier et de l'eau ; matériel saisi (motopompes, groupe électrogène) et un lot important (concasseurs, laveries, tapis de concentration) détruit sur place.",
    "status": "En cours",
    "observations": "Procédure judiciaire ouverte contre les 16 personnes interpellées."
  },
  {
    "orderNumber": 79,
    "trackingId": "VEILLE-2026-079",
    "dateOfFacts": "05-09/09/2026",
    "source": "L'Inter n°8448 (09/09) ; Le Patriote n°7988 (10/09)",
    "region": "Région du Tonkpi",
    "locality": "Man et département (Danané, Zouan-Hounien, Biankouma)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le député de Man, Albert Flindé, a appelé le 5/09 la chefferie traditionnelle à s'impliquer contre l'orpaillage illégal, dénonçant la complicité de certains membres locaux, y compris parfois des chefs de village, et exhortant les garants de la tradition à refuser systématiquement toute autorisation sollicitée. Il a annoncé une mission d'information parlementaire du 23 au 27 septembre dans le Tonkpi (Danané, Zouan-Hounien, Biankouma, étape finale à Man). Lors de la 4e édition de la Semaine des chefs de Man (5/09), il a relayé le même message auprès des chefs de terre et de village, appelant aussi la jeunesse à un usage responsable des réseaux sociaux après une agression récente dans la région.",
    "status": "À suivre",
    "observations": "Mention d'un incident récent (agression liée aux réseaux sociaux) dans le Tonkpi, non détaillé dans les fiches disponibles."
  },
  {
    "orderNumber": 80,
    "trackingId": "VEILLE-2026-080",
    "dateOfFacts": "07/09/2026 (directive) ; 09/09 (installation CTL)",
    "source": "L'Inter n°8448 (09/09) ; L'Inter n°8449 (10/09)",
    "region": "Région de la Marahoué",
    "locality": "Bouaflé et Pakouabo",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le préfet de la Marahoué a annoncé le 7/09 que l'ensemble des préfets du pays ont reçu la directive d'éradiquer l'orpaillage illégal dans leurs circonscriptions d'ici six mois, avec évaluation et sanctions en cas de complicités récurrentes ; il appelle à remonter toute la chaîne de valeur occulte (« Qui achète l'or ? Qui finance ces activités ? ») et à briser l'omerta. Le 9/09, une caravane de sensibilisation à Pakouabo (ONG Case et Impact) a marqué l'installation du Comité technique local (CTL) du département de Bouaflé, chargé de coordonner la lutte et d'accélérer la formalisation de l'exploitation artisanale.",
    "status": "En cours",
    "observations": "Ultimatum national de six mois fixé par le gouvernement (applicable à toutes les régions)."
  },
  {
    "orderNumber": 81,
    "trackingId": "VEILLE-2026-081",
    "dateOfFacts": "08/09/2026",
    "source": "Le Patriote n°7988 (10/09)",
    "region": "Région du Gbôklé",
    "locality": "Fresco",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Le préfet de Fresco a annoncé la mise en mission du corps préfectoral pour mettre fin à l'orpaillage illégal dans un délai de six mois, avec évaluation et sanctions en cas de complicités récurrentes. Il a salué la résilience des chefs de Fresco qui n'ont pas cédé au phénomène, contrairement aux départements voisins de Sassandra et Grand-Lahou.",
    "status": "En cours",
    "observations": "Fresco cité comme contre-exemple positif face au dossier CNRA/Sassandra déjà largement documenté dans ce tableau."
  },
  {
    "orderNumber": 82,
    "trackingId": "VEILLE-2026-082",
    "dateOfFacts": "09/09/2026 (témoignage)",
    "source": "Soir Info n°9545 (09/09)",
    "region": "Région du Moronou",
    "locality": "Moronou (localisation précise non donnée)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Un ancien contrôleur de sites d'orpaillage illégal, identifié par les initiales O.V. et surnommé « Vétcho », témoigne alors qu'il s'apprête à quitter la région par crainte de l'arrivée des forces de sécurité. Il affirme avoir récolté environ 600 grammes d'or vendus à un acheteur de Dimbokro, évoque l'implication d'« autorités villageoises et administratives » sans donner de détails, reconnaît les dégâts causés (champs détruits, trous béants) et dit vouloir quitter cette activité jugée trop risquée.",
    "status": "Clos (départ du témoin)",
    "observations": "Témoignage de première main rare, à mobiliser avec prudence (source anonymisée, non vérifiable de manière indépendante)."
  },
  {
    "orderNumber": 83,
    "trackingId": "VEILLE-2026-083",
    "dateOfFacts": "30/08/2026 (contribution)",
    "source": "Soir Info n°9538 (01/09)",
    "region": "Portée nationale",
    "locality": "Non localisé (contribution d'opinion)",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "L'ex-président de l'UNJCI, Jean-Claude Coulibaly, plaide pour déplacer le regard porté sur l'orpaillage clandestin des exécutants vers les financiers : « Derrière la pioche, il y a souvent un portefeuille. Derrière le portefeuille, un réseau. » Il décrit une bombe sociale et sécuritaire pour les localités concernées (afflux de population dépassant les capacités d'accueil en eau, écoles, santé, sécurité) et des dérives associées (trafics, drogue, prostitution, armes).",
    "status": "À suivre",
    "observations": "Appel à cibler les financeurs plutôt que les seuls petits exploitants, thème repris dans plusieurs interventions officielles de la même semaine."
  },
  {
    "orderNumber": 84,
    "trackingId": "VEILLE-2026-084",
    "dateOfFacts": "Analyse publiée le 02/09 (référence : saisie de Dimbokro)",
    "source": "L'Essor Ivoirien n°2057 (02/09)",
    "region": "Portée nationale",
    "locality": "Dimbokro (exemple cité) et Dabakala",
    "category": "Conflit",
    "conflictType": "Orpaillage",
    "description": "Une analyse pointe la dimension sécuritaire de l'orpaillage illégal à travers l'usage croissant de dynamite, illustré par la destruction de 496 bâtons de dynamite saisis par la gendarmerie de Dimbokro. La loi n°98-749 du 23 décembre 1998 encadre strictement la vente et la détention d'explosifs, mais resterait peu dissuasive du fait de la porosité des frontières et de la corruption ; des interventions à Dabakala révéleraient un système de surveillance largement inefficace. Le texte relie le phénomène au contexte régional de montée du terrorisme en Afrique de l'Ouest.",
    "status": "En cours",
    "observations": "Angle sécuritaire distinct des dimensions environnementale et sociale déjà largement documentées."
  }
];
